import * as TJS from 'json-schema-to-typescript';
import fs from 'fs';
import jsYaml from 'js-yaml';
import { ExpandSchemaCommand } from './expand';

export class TypesSchemaCommand {
  static async execute(inputFilePath: string, outputFilePath: string) {
    const schema = jsYaml.load(fs.readFileSync(inputFilePath, 'utf8'));

    const expandedSchema = ExpandSchemaCommand.expand(schema);

    const types = await TJS.compile(expandedSchema, 'config', { bannerComment: '/* Autogenerated code */' });

    fs.writeFileSync(outputFilePath, types);
  }
}
