/* Autogenerated code */

export interface Config {
  apps: {
    api: {
      urls: {
        prefix: string;
      };
    };
  };
  libs: {
    common: {
      urls: {
        api: string;
      };
      redis: {
        host: string;
        port: number;
      };
    };
  };
}
